name: Linux XDP

on:
  workflow_dispatch:

jobs:
  linux-xdp:
    runs-on: [self-hosted, linux, x64, xdp]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - name: Build eBPF object
        run: cargo xtask build-ebpf
      - name: Run ignored liquid agent XDP integration test
        run: sudo cargo test -p liquid-agent --test linux_agent_tests -- --ignored
